(function(){
'use strict';
var OWNER='phatnbt',REPO='sontienbao-v7',BRANCH='main',PRODUCT_FILE='manual-products.js',CONTENT_FILE='v7-content.js',DRAFT_KEY='stb-admin-v2-draft';
var productState=clone(window.STB_MANUAL_PRODUCTS||{version:1,updatedAt:null,additions:[],overrides:{},hidden:[]});
var contentState=clone(window.STB_V7_CONTENT||{}),contentInitial=clone(contentState);
var base=Array.isArray(window.STB_PRODUCTS_BEFORE_MANUAL)?window.STB_PRODUCTS_BEFORE_MANUAL.slice():[];
var productSha='',contentSha='',productDirty=false,contentDirty=false,currentEdit=null,uploadContext=null;
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
function clone(v){return JSON.parse(JSON.stringify(v));}
function token(){return sessionStorage.getItem('stb-v7-github-token')||'';}
function setToken(v){if(v)sessionStorage.setItem('stb-v7-github-token',v);else sessionStorage.removeItem('stb-v7-github-token');}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function normUrl(u){return String(u||'').trim().replace(/\/$/,'');}
function pkey(p){if(p&&p.id)return'id:'+p.id;if(p&&p.url)return'url:'+normUrl(p.url);return'id:manual-'+Date.now();}
function money(v){v=Number(v||0);return v?v.toLocaleString('vi-VN')+' ₫':'Liên hệ';}
function toast(msg,type){var el=$('#toast');el.textContent=msg;el.className='toast show '+(type||'');clearTimeout(el._t);el._t=setTimeout(function(){el.className='toast';},4200);}
function getPath(obj,path){return path.split('.').reduce(function(o,k){return o==null?undefined:o[k];},obj);}
function setPath(obj,path,val){var a=path.split('.'),o=obj;for(var i=0;i<a.length-1;i++){var k=a[i],n=a[i+1];if(o[k]==null)o[k]=/^\d+$/.test(n)?[]:{};o=o[k];}o[a[a.length-1]]=val;}
function encode64(s){var u=new TextEncoder().encode(s),b='',chunk=0x8000;for(var i=0;i<u.length;i+=chunk)b+=String.fromCharCode.apply(null,u.subarray(i,i+chunk));return btoa(b);}
function decode64(s){var b=atob(String(s||'').replace(/\s/g,'')),u=new Uint8Array(b.length);for(var i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new TextDecoder().decode(u);}
async function api(path,opts){var t=token();if(!t)throw new Error('Chưa kết nối GitHub.');opts=opts||{};var headers=Object.assign({'Accept':'application/vnd.github+json','Authorization':'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'},opts.headers||{});if(opts.body)headers['Content-Type']='application/json';var r=await fetch('https://api.github.com'+path,Object.assign({},opts,{headers:headers}));var body=null;try{body=await r.json();}catch(e){}if(!r.ok)throw new Error((body&&body.message)||('GitHub API '+r.status));return body;}
function parseAssign(text,name){var re=new RegExp('window\\.'+name+'\\s*=\\s*(\\{[\\s\\S]*\\})\\s*;?\\s*$'),m=text.match(re);if(!m)throw new Error('Không đọc được '+name);return JSON.parse(m[1]);}
function serializeProducts(){productState.version=1;productState.updatedAt=new Date().toISOString();return'window.STB_MANUAL_PRODUCTS = '+JSON.stringify(productState,null,2)+';\n';}
function serializeContent(){contentState.meta=contentState.meta||{};contentState.meta.updatedAt=new Date().toISOString();contentState.meta.source='admin-v2';return'window.STB_V7_CONTENT = '+JSON.stringify(contentState,null,2)+';\n';}
function dirtyAny(){return productDirty||contentDirty;}
function updateSaveUI(){var dirty=dirtyAny(),b=$('#saveBtn'),s=$('#saveState');b.textContent=dirty?'Lưu thay đổi':'Đã lưu';s.innerHTML=dirty?'<span class="dirty-dot"></span>Có thay đổi chưa lưu':'<span class="saved-dot"></span>Không có thay đổi chưa lưu';saveDraft();}
function markProductDirty(){productDirty=true;updateSaveUI();}
function markContentDirty(){contentDirty=true;updateSaveUI();}
function saveDraft(){if(!dirtyAny())return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({savedAt:new Date().toISOString(),products:productState,content:contentState,productDirty:productDirty,contentDirty:contentDirty}));renderDraftInfo();}catch(e){}}
function clearDraft(){localStorage.removeItem(DRAFT_KEY);renderDraftInfo();}
function renderDraftInfo(){var el=$('#draftInfo');if(!el)return;try{var d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');el.textContent=d&&d.savedAt?'Có nháp: '+new Date(d.savedAt).toLocaleString('vi-VN'):'Chưa có nháp cục bộ.';}catch(e){el.textContent='Chưa có nháp cục bộ.';}}
function restoreDraft(){try{var d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d){toast('Không có nháp để khôi phục.');return;}if(d.products)productState=d.products;if(d.content)contentState=d.content;productDirty=!!d.productDirty;contentDirty=!!d.contentDirty;renderAll();updateSaveUI();toast('Đã khôi phục nháp trên thiết bị.','ok');}catch(e){toast('Nháp không hợp lệ.','err');}}
function setConn(ok,text){var el=$('#connBadge');el.className='tag '+(ok?'ok':'hidden');el.textContent=text||(ok?'Đã kết nối':'Chưa kết nối');}
async function connect(){var v=$('#tokenInput').value.trim();if(v)setToken(v);try{var repo=await api('/repos/'+OWNER+'/'+REPO);if(repo.permissions&&repo.permissions.push===false)throw new Error('Token chưa có quyền ghi repository.');setConn(true,'GitHub đã kết nối');$('#tokenInput').value='';await loadRemote();toast('Kết nối GitHub thành công.','ok');}catch(e){setConn(false,'Kết nối lỗi');toast(e.message,'err');}}
async function loadRemote(){try{var files=await Promise.all([api('/repos/'+OWNER+'/'+REPO+'/contents/'+PRODUCT_FILE+'?ref='+BRANCH),api('/repos/'+OWNER+'/'+REPO+'/contents/'+CONTENT_FILE+'?ref='+BRANCH)]);productState=parseAssign(decode64(files[0].content),'STB_MANUAL_PRODUCTS');contentState=parseAssign(decode64(files[1].content),'STB_V7_CONTENT');contentInitial=clone(contentState);productSha=files[0].sha||'';contentSha=files[1].sha||'';productDirty=false;contentDirty=false;clearDraft();renderAll();updateSaveUI();toast('Đã tải dữ liệu mới nhất từ GitHub.','ok');}catch(e){toast('Không tải được dữ liệu: '+e.message,'err');}}
async function saveOne(file,sha,content,message){var body={message:message,content:encode64(content),branch:BRANCH};if(sha)body.sha=sha;return api('/repos/'+OWNER+'/'+REPO+'/contents/'+file,{method:'PUT',body:JSON.stringify(body)});}
async function saveRemote(){if(!dirtyAny()){toast('Không có thay đổi mới.');return;}if(!token()){showPage('settings');toast('Hãy kết nối GitHub trước khi lưu.','err');return;}var b=$('#saveBtn');try{b.disabled=true;b.textContent='Đang lưu…';if(contentDirty){var cr=await saveOne(CONTENT_FILE,contentSha,serializeContent(),'Update V7 content from Admin V2');contentSha=cr.content&&cr.content.sha||contentSha;contentDirty=false;}if(productDirty){var pr=await saveOne(PRODUCT_FILE,productSha,serializeProducts(),'Update V7 manual products from Admin V2');productSha=pr.content&&pr.content.sha||productSha;productDirty=false;}clearDraft();updateSaveUI();toast('Đã lưu thành công. GitHub Pages đang cập nhật V7.','ok');checkDeploy();}catch(e){toast('Lưu thất bại: '+e.message+' — nếu file vừa thay đổi ở nơi khác, bấm Tải lại rồi thử lại.','err');updateSaveUI();}finally{b.disabled=false;}}
async function checkDeploy(){var badge=$('#deployBadge');try{var r=await fetch('https://api.github.com/repos/'+OWNER+'/'+REPO+'/pages');var j=await r.json();var st=j.status||'unknown';badge.textContent='Pages: '+st;badge.className='tag '+(st==='built'?'ok':st==='errored'?'hidden':'manual');}catch(e){badge.textContent='Pages';}}
function manualFor(p){var k=pkey(p);return productState.overrides&&productState.overrides[k]?productState.overrides[k]:null;}
function isHidden(p){return Array.isArray(productState.hidden)&&productState.hidden.indexOf(pkey(p))>=0;}
function resolveProducts(){var items=base.map(function(p){var o=manualFor(p);return o?Object.assign({},p,o,{manualOverride:true}):Object.assign({},p);});var map={};items.forEach(function(p){map[pkey(p)]=true;});(productState.additions||[]).forEach(function(p){if(p&&!map[pkey(p)])items.push(Object.assign({manualOnly:true,enabled:true},p));});return items;}
function sourceOf(p){if(p.manualOnly)return'manual';if(manualFor(p))return'override';if(isHidden(p))return'hidden';return'sync';}
function sourceTag(p){var s=sourceOf(p);if(s==='manual')return'<span class="tag manual">Thêm thủ công</span>';if(s==='override')return'<span class="tag manual">Đã sửa thủ công</span>';if(s==='hidden')return'<span class="tag hidden">Đang ẩn</span>';return'<span class="tag sync">Tự đồng bộ</span>';}
function renderStats(){var r=resolveProducts();$('#statTotal').textContent=r.filter(function(p){return !isHidden(p)&&p.enabled!==false;}).length;$('#statSynced').textContent=base.length;$('#statOverride').textContent=Object.keys(productState.overrides||{}).length;$('#statHidden').textContent=(productState.hidden||[]).length;}
function getTableProducts(){return resolveProducts();}
function renderProducts(){var rows=$('#productRows');if(!rows)return;var q=String($('#productSearch').value||'').toLowerCase(),filter=$('#sourceFilter').value,list=getTableProducts().filter(function(p){var source=sourceOf(p);if(filter!=='all'&&source!==filter)return false;var hay=[p.name,p.brand,p.category,p.url].join(' ').toLowerCase();return !q||hay.indexOf(q)>=0;});rows.innerHTML='';$('#productEmpty').style.display=list.length?'none':'block';list.forEach(function(p){var tr=document.createElement('tr'),hidden=isHidden(p),source=sourceOf(p);tr.innerHTML='<td><div style="display:flex;align-items:center;gap:10px"><img src="'+esc(p.image||'assets/logo-tien-bao.png')+'" alt=""><div><div class="product-name">'+esc(p.name||'Sản phẩm')+'</div><div class="muted">'+esc(p.brand||'')+'</div></div></div></td><td>'+sourceTag(p)+'</td><td>'+esc(p.category||'—')+'</td><td><b>'+esc(money(p.price))+'</b>'+(p.oldPrice?'<div class="muted"><s>'+esc(money(p.oldPrice))+'</s></div>':'')+'</td><td>'+(hidden?'<span class="tag hidden">Ẩn</span>':(p.enabled===false?'<span class="tag hidden">Tắt</span>':'<span class="tag ok">Hiển thị</span>'))+'</td><td><div class="actions"><button class="mini" data-edit>Sửa</button>'+(source==='override'?'<button class="mini" data-restore>Trả về sync</button>':'')+(hidden?'<button class="mini" data-show>Hiện lại</button>':'<button class="mini" data-hide>Ẩn</button>')+(source==='manual'?'<button class="mini" data-delete>Xóa</button>':'')+'</div></td>';rows.appendChild(tr);tr.querySelector('[data-edit]').onclick=function(){openEdit(p);};var b=tr.querySelector('[data-restore]');if(b)b.onclick=function(){delete productState.overrides[pkey(p)];productState.hidden=productState.hidden.filter(function(k){return k!==pkey(p);});markProductDirty();renderProducts();renderStats();};b=tr.querySelector('[data-hide]');if(b)b.onclick=function(){if(productState.hidden.indexOf(pkey(p))<0)productState.hidden.push(pkey(p));markProductDirty();renderProducts();renderStats();};b=tr.querySelector('[data-show]');if(b)b.onclick=function(){productState.hidden=productState.hidden.filter(function(k){return k!==pkey(p);});markProductDirty();renderProducts();renderStats();};b=tr.querySelector('[data-delete]');if(b)b.onclick=function(){if(confirm('Xóa sản phẩm thủ công này?')){productState.additions=productState.additions.filter(function(x){return pkey(x)!==pkey(p);});markProductDirty();renderProducts();renderStats();}};});}
function fillProductForm(p){$('#fName').value=p.name||'';$('#fBrand').value=p.brand||'';$('#fCategory').value=p.category||'';$('#fBadge').value=p.badge||'';$('#fDescription').value=p.description||'';$('#fPrice').value=Number(p.price||0);$('#fOldPrice').value=Number(p.oldPrice||0);$('#fPricePrefix').value=p.pricePrefix||'';$('#fUnit').value=p.unit||'';$('#fUrl').value=p.url||'';$('#fImage').value=p.image||'';$('#fFeatured').checked=p.featured===true;$('#fEnabled').checked=p.enabled!==false;updateProductPreview();}
function openEdit(p){currentEdit=p;$('#modalTitle').textContent=p.manualOnly?'Sửa sản phẩm thủ công':'Chỉnh sửa sản phẩm';$('#editKey').value=pkey(p);$('#editMode').value=p.manualOnly?'manual':'override';fillProductForm(p);$('#productModal').classList.add('show');}
function openAdd(){var p={id:'manual-'+Date.now(),name:'',brand:'JOTUN',category:'Sản phẩm',description:'',image:'',price:0,oldPrice:0,pricePrefix:'',unit:'',badge:'',featured:true,enabled:true,url:'',manualOnly:true};currentEdit=p;$('#modalTitle').textContent='Thêm sản phẩm mới';$('#editKey').value=pkey(p);$('#editMode').value='new';fillProductForm(p);$('#productModal').classList.add('show');}
function closeModal(){$('#productModal').classList.remove('show');currentEdit=null;}
function productFormData(){return{name:$('#fName').value.trim(),brand:$('#fBrand').value.trim(),category:$('#fCategory').value.trim(),badge:$('#fBadge').value.trim(),description:$('#fDescription').value.trim(),price:Number($('#fPrice').value||0),oldPrice:Number($('#fOldPrice').value||0),pricePrefix:$('#fPricePrefix').value.trim(),unit:$('#fUnit').value.trim(),url:$('#fUrl').value.trim(),image:$('#fImage').value.trim(),featured:$('#fFeatured').checked,enabled:$('#fEnabled').checked};}
function submitProduct(e){e.preventDefault();var data=productFormData(),mode=$('#editMode').value,key=$('#editKey').value;if(!data.name){toast('Tên sản phẩm không được để trống.','err');return;}if(mode==='new'){data.id=key.replace(/^id:/,'');data.manualOnly=true;productState.additions.push(data);}else if(mode==='manual'){var idx=productState.additions.findIndex(function(p){return pkey(p)===key;});if(idx>=0)productState.additions[idx]=Object.assign({},productState.additions[idx],data);}else{productState.overrides[key]=data;productState.hidden=productState.hidden.filter(function(k){return k!==key;});}markProductDirty();closeModal();renderProducts();renderStats();toast('Đã áp dụng. Bấm Lưu thay đổi để cập nhật V7.','ok');}
function updateProductPreview(){$('#imagePreview').src=$('#fImage').value.trim()||'assets/logo-tien-bao.png';}
function bindContentInputs(){$$('[data-content]').forEach(function(el){var path=el.dataset.content,v=getPath(contentState,path);if(el.type==='checkbox')el.checked=!!v;else el.value=v==null?'':v;el.oninput=function(){var val=el.type==='checkbox'?el.checked:(el.type==='number'?Number(el.value||0):el.value);setPath(contentState,path,val);markContentDirty();updateContentPreview(path);renderSeoPreview();};});$$('[data-preview-content]').forEach(function(el){updateContentPreview(el.dataset.previewContent);});}
function updateContentPreview(path){var el=document.querySelector('[data-preview-content="'+path+'"]');if(el)el.src=getPath(contentState,path)||'assets/logo-tien-bao.png';}
function renderCategories(){var root=$('#categoryEditorList');if(!root)return;root.innerHTML='';(contentState.categories||[]).forEach(function(c,i){var box=document.createElement('div');box.className='list-item';box.innerHTML='<div class="list-head"><b>'+esc(c.name||('Danh mục '+(i+1)))+'</b><span class="drag-note">#'+(i+1)+'</span><button class="mini" data-up>↑</button><button class="mini" data-down>↓</button><button class="mini" data-dup>Nhân bản</button><button class="mini" data-del>Xóa</button></div><div class="grid"><label class="check full"><input type="checkbox" data-en> Hiển thị</label><div class="field"><label>Tên</label><input data-k="name"></div><div class="field"><label>URL</label><input data-k="url"></div><div class="field full"><label>Mô tả</label><input data-k="description"></div><div class="field full"><label>Ảnh</label><div class="preview-row"><img data-cat-img alt=""><div><input data-k="image"><div class="inline-actions"><button type="button" class="btn mini-btn" data-upload>Tải ảnh</button></div></div></div></div></div>';root.appendChild(box);var en=box.querySelector('[data-en]');en.checked=c.enabled!==false;en.onchange=function(){contentState.categories[i].enabled=en.checked;markContentDirty();};box.querySelectorAll('[data-k]').forEach(function(inp){var k=inp.dataset.k;inp.value=c[k]||'';inp.oninput=function(){contentState.categories[i][k]=inp.value;if(k==='image')box.querySelector('[data-cat-img]').src=inp.value||'assets/logo-tien-bao.png';if(k==='name')box.querySelector('.list-head b').textContent=inp.value||('Danh mục '+(i+1));markContentDirty();};});box.querySelector('[data-cat-img]').src=c.image||'assets/logo-tien-bao.png';box.querySelector('[data-upload]').onclick=function(){uploadContext={type:'category',index:i};$('#filePicker').click();};box.querySelector('[data-up]').onclick=function(){if(i>0){var x=contentState.categories.splice(i,1)[0];contentState.categories.splice(i-1,0,x);markContentDirty();renderCategories();}};box.querySelector('[data-down]').onclick=function(){if(i<contentState.categories.length-1){var x=contentState.categories.splice(i,1)[0];contentState.categories.splice(i+1,0,x);markContentDirty();renderCategories();}};box.querySelector('[data-dup]').onclick=function(){var x=clone(c);x.id='cat-'+Date.now();x.name=(x.name||'Danh mục')+' (bản sao)';contentState.categories.splice(i+1,0,x);markContentDirty();renderCategories();};box.querySelector('[data-del]').onclick=function(){if(confirm('Xóa danh mục này?')){contentState.categories.splice(i,1);markContentDirty();renderCategories();}};});}
function renderFaqs(){var root=$('#faqEditorList');if(!root)return;root.innerHTML='';(contentState.faqs||[]).forEach(function(f,i){var box=document.createElement('div');box.className='list-item';box.innerHTML='<div class="list-head"><b>FAQ '+(i+1)+'</b><button class="mini" data-up>↑</button><button class="mini" data-down>↓</button><button class="mini" data-dup>Nhân bản</button><button class="mini" data-del>Xóa</button></div><div class="grid one"><label class="check"><input type="checkbox" data-en> Hiển thị</label><div class="field"><label>Câu hỏi</label><input data-q></div><div class="field"><label>Trả lời</label><textarea data-a></textarea></div></div>';root.appendChild(box);box.querySelector('[data-en]').checked=f.enabled!==false;box.querySelector('[data-en]').onchange=function(e){contentState.faqs[i].enabled=e.target.checked;markContentDirty();};box.querySelector('[data-q]').value=f.question||'';box.querySelector('[data-q]').oninput=function(e){contentState.faqs[i].question=e.target.value;markContentDirty();};box.querySelector('[data-a]').value=f.answer||'';box.querySelector('[data-a]').oninput=function(e){contentState.faqs[i].answer=e.target.value;markContentDirty();};box.querySelector('[data-up]').onclick=function(){if(i>0){var x=contentState.faqs.splice(i,1)[0];contentState.faqs.splice(i-1,0,x);markContentDirty();renderFaqs();}};box.querySelector('[data-down]').onclick=function(){if(i<contentState.faqs.length-1){var x=contentState.faqs.splice(i,1)[0];contentState.faqs.splice(i+1,0,x);markContentDirty();renderFaqs();}};box.querySelector('[data-dup]').onclick=function(){var x=clone(f);x.id='faq-'+Date.now();x.question=(x.question||'Câu hỏi')+' (bản sao)';contentState.faqs.splice(i+1,0,x);markContentDirty();renderFaqs();};box.querySelector('[data-del]').onclick=function(){if(confirm('Xóa FAQ này?')){contentState.faqs.splice(i,1);markContentDirty();renderFaqs();}};});}
function addCategory(){contentState.categories=contentState.categories||[];contentState.categories.push({id:'cat-'+Date.now(),name:'Danh mục mới',description:'',image:'',url:'https://sontienbao.com/san-pham/',enabled:true});markContentDirty();renderCategories();}
function addFaq(){contentState.faqs=contentState.faqs||[];contentState.faqs.push({id:'faq-'+Date.now(),question:'Câu hỏi mới',answer:'Nhập câu trả lời tại đây.',enabled:true});markContentDirty();renderFaqs();}
function renderSeoPreview(){var t=String(getPath(contentState,'seo.title')||''),d=String(getPath(contentState,'seo.description')||'');$('#seoTitleCount').textContent=t.length+'/60';$('#seoDescCount').textContent=d.length+'/160';$('#googleTitle').textContent=t||'Tiêu đề website';$('#googleDescription').textContent=d||'Mô tả website';}
function resetSection(name){if(!contentInitial[name])return;if(!confirm('Khôi phục section '+name+' về dữ liệu đã tải gần nhất?'))return;contentState[name]=clone(contentInitial[name]);markContentDirty();renderContent();toast('Đã hoàn tác section '+name+'.');}
function renderContent(){if(!contentState.banners||!contentState.banners.length)contentState.banners=[{id:'banner-1',enabled:true,title:'',subtitle:'',ctaLabel:'',ctaUrl:'#calculator',image:''}];if(!contentState.popups||!contentState.popups.length)contentState.popups=[{id:'popup-1',enabled:false,title:'',body:'',highlight:'',image:'',ctaLabel:'Xem chi tiết',ctaUrl:'https://sontienbao.com/',secondaryLabel:'Để sau',delay:1100}];bindContentInputs();renderCategories();renderFaqs();renderSeoPreview();}
function renderAll(){renderStats();renderProducts();renderContent();renderDraftInfo();renderUpdatedInfo();}
function renderUpdatedInfo(){var el=$('#lastUpdatedInfo');if(!el)return;var c=contentState.meta&&contentState.meta.updatedAt,p=productState.updatedAt;el.textContent='Nội dung: '+(c?new Date(c).toLocaleString('vi-VN'):'chưa có')+' • Sản phẩm thủ công: '+(p?new Date(p).toLocaleString('vi-VN'):'chưa có');}
function fileBase64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(String(r.result||'').split(',')[1]||'');};r.onerror=reject;r.readAsDataURL(file);});}
function slug(s){return String(s||'image').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9.]+/g,'-').replace(/^-+|-+$/g,'');}
async function uploadFile(file){if(!file)return;if(!token()){showPage('settings');toast('Kết nối GitHub trước khi upload ảnh.','err');return;}if(file.size>8*1024*1024){toast('Ảnh lớn hơn 8MB. Hãy nén ảnh trước.','err');return;}try{var folder=uploadContext&&uploadContext.type==='product'?'products':'content',path='assets/admin/'+folder+'/'+Date.now()+'-'+slug(file.name);await api('/repos/'+OWNER+'/'+REPO+'/contents/'+path,{method:'PUT',body:JSON.stringify({message:'Upload image from Admin V2',content:await fileBase64(file),branch:BRANCH})});if(uploadContext&&uploadContext.type==='product'){$('#fImage').value=path;updateProductPreview();markProductDirty();}else if(uploadContext&&uploadContext.type==='category'){contentState.categories[uploadContext.index].image=path;markContentDirty();renderCategories();}else if(uploadContext&&uploadContext.type==='content'){setPath(contentState,uploadContext.path,path);markContentDirty();renderContent();}toast('Đã tải ảnh lên GitHub.','ok');}catch(e){toast('Upload ảnh thất bại: '+e.message,'err');}finally{uploadContext=null;}}
function exportData(){var blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),content:contentState,manualProducts:productState},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sontienbao-v7-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href);},500);}
function showPage(name){$$('.page').forEach(function(p){p.classList.toggle('active',p.id==='page-'+name);});$$('.nav [data-page]').forEach(function(b){b.classList.toggle('active',b.dataset.page===name);});var names={dashboard:'Dashboard',products:'Sản phẩm',content:'Nội dung trang',seo:'SEO & giao diện',settings:'Kết nối & dữ liệu'};$('#pageTitle').textContent=names[name]||'Admin V2';location.hash=name;}
function bindStatic(){
  $$('[data-page]').forEach(function(b){b.onclick=function(){showPage(b.dataset.page);};});
  $$('[data-go]').forEach(function(b){b.onclick=function(){showPage(b.dataset.go);var id=b.dataset.focus;if(id)setTimeout(function(){var el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});},50);};});
  $('#themeBtn').onclick=function(){document.body.classList.toggle('dark');localStorage.setItem('stb-admin-v2-theme',document.body.classList.contains('dark')?'dark':'light');};
  $('#previewBtn').onclick=function(){window.open('./','_blank','noopener');};
  $('#connectBtn').onclick=connect;$('#disconnectBtn').onclick=function(){setToken('');setConn(false,'Chưa kết nối');toast('Đã xóa token khỏi phiên trình duyệt.');};$('#reloadBtn').onclick=loadRemote;$('#saveBtn').onclick=saveRemote;
  $('#addProductBtn').onclick=openAdd;$('#productForm').onsubmit=submitProduct;$('#cancelModal').onclick=closeModal;$('#closeModalX').onclick=closeModal;$('#productModal').onclick=function(e){if(e.target===this)closeModal();};$('#productSearch').oninput=renderProducts;$('#sourceFilter').onchange=renderProducts;$('#fImage').oninput=updateProductPreview;$('#uploadImageBtn').onclick=function(){uploadContext={type:'product'};$('#filePicker').click();};$('#clearProductImage').onclick=function(){$('#fImage').value='';updateProductPreview();};
  $('#addCategoryBtn').onclick=addCategory;$('#addFaqBtn').onclick=addFaq;$('#restoreDraftBtn').onclick=restoreDraft;$('#clearDraftBtn').onclick=function(){clearDraft();toast('Đã xóa nháp trên thiết bị.');};$('#exportBtn').onclick=exportData;
  $$('[data-upload-content]').forEach(function(b){b.onclick=function(){uploadContext={type:'content',path:b.dataset.uploadContent};$('#filePicker').click();};});$$('[data-clear-content]').forEach(function(b){b.onclick=function(){setPath(contentState,b.dataset.clearContent,'');markContentDirty();renderContent();};});$$('[data-reset-section]').forEach(function(b){b.onclick=function(){resetSection(b.dataset.resetSection);};});
  $('#filePicker').onchange=function(){var f=this.files&&this.files[0];this.value='';uploadFile(f);};
  window.addEventListener('beforeunload',function(e){if(dirtyAny()){e.preventDefault();e.returnValue='';}});
}
if(localStorage.getItem('stb-admin-v2-theme')==='dark')document.body.classList.add('dark');
bindStatic();renderAll();updateSaveUI();checkDeploy();var initialHash=location.hash.replace('#','');if(['dashboard','products','content','seo','settings'].indexOf(initialHash)>=0)showPage(initialHash);if(token()){setConn(true,'Đang kiểm tra…');connect();}else setConn(false,'Chưa kết nối');
})();
