(function(){
'use strict';
var OWNER='phatnbt',REPO='sontienbao-v7',BRANCH='main',CONTENT_FILE='v7-content.js',DRAFT_KEY='stb-admin-content-draft-v1';
var contentState=clone(window.STB_V7_CONTENT||{}),contentInitial=clone(contentState),contentSha='',contentDirty=false,uploadContext=null;
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
function clone(v){return JSON.parse(JSON.stringify(v==null?{}:v));}
function token(){return sessionStorage.getItem('stb-v7-github-token')||'';}
function setToken(v){if(v)sessionStorage.setItem('stb-v7-github-token',v);else sessionStorage.removeItem('stb-v7-github-token');}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function getPath(obj,path){return path.split('.').reduce(function(o,k){return o==null?undefined:o[k];},obj);}
function setPath(obj,path,val){var a=path.split('.'),o=obj;for(var i=0;i<a.length-1;i++){var k=a[i],n=a[i+1];if(o[k]==null)o[k]=/^\d+$/.test(n)?[]:{};o=o[k];}o[a[a.length-1]]=val;}
function encode64(s){var u=new TextEncoder().encode(s),b='',chunk=0x8000;for(var i=0;i<u.length;i+=chunk)b+=String.fromCharCode.apply(null,u.subarray(i,i+chunk));return btoa(b);}
function decode64(s){var b=atob(String(s||'').replace(/\s/g,'')),u=new Uint8Array(b.length);for(var i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new TextDecoder().decode(u);}
function toast(msg,type){var el=$('#toast');if(!el)return;el.textContent=msg;el.className='toast show '+(type||'');clearTimeout(el._t);el._t=setTimeout(function(){el.className='toast';},4200);}
async function api(path,opts){var t=token();if(!t)throw new Error('Chưa kết nối GitHub.');opts=opts||{};var headers=Object.assign({'Accept':'application/vnd.github+json','Authorization':'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'},opts.headers||{});if(opts.body)headers['Content-Type']='application/json';var r=await fetch('https://api.github.com'+path,Object.assign({},opts,{headers:headers}));var body=null;try{body=await r.json();}catch(e){}if(!r.ok)throw new Error((body&&body.message)||('GitHub API '+r.status));return body;}
function parseAssign(text){var m=text.match(/window\.STB_V7_CONTENT\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);if(!m)throw new Error('Không đọc được v7-content.js');return JSON.parse(m[1]);}
function serializeContent(){contentState.meta=contentState.meta||{};contentState.meta.updatedAt=new Date().toISOString();contentState.meta.source='admin-center-content-only';return'window.STB_V7_CONTENT = '+JSON.stringify(contentState,null,2)+';\n';}
function markDirty(){contentDirty=true;updateSaveUI();}
function updateSaveUI(){var b=$('#saveBtn'),s=$('#saveState');if(b)b.textContent=contentDirty?'Lưu thay đổi':'Đã lưu';if(s)s.innerHTML=contentDirty?'<span class="dirty-dot"></span>Có thay đổi chưa lưu':'<span class="saved-dot"></span>Không có thay đổi chưa lưu';saveDraft();}
function saveDraft(){if(!contentDirty)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify({savedAt:new Date().toISOString(),content:contentState}));renderDraftInfo();}catch(e){}}
function clearDraft(){localStorage.removeItem(DRAFT_KEY);renderDraftInfo();}
function renderDraftInfo(){var el=$('#draftInfo');if(!el)return;try{var d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');el.textContent=d&&d.savedAt?'Có nháp nội dung: '+new Date(d.savedAt).toLocaleString('vi-VN'):'Chưa có nháp cục bộ.';}catch(e){el.textContent='Chưa có nháp cục bộ.';}}
function restoreDraft(){try{var d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d||!d.content){toast('Không có nháp để khôi phục.');return;}contentState=d.content;contentDirty=true;renderAll();updateSaveUI();toast('Đã khôi phục nháp nội dung.','ok');}catch(e){toast('Nháp không hợp lệ.','err');}}
function setConn(ok,text){var el=$('#connBadge');if(!el)return;el.className='tag '+(ok?'ok':'hidden');el.textContent=text||(ok?'Đã kết nối':'Chưa kết nối');}
async function connect(){var input=$('#tokenInput'),v=input?input.value.trim():'';if(v)setToken(v);try{var repo=await api('/repos/'+OWNER+'/'+REPO);if(repo.permissions&&repo.permissions.push===false)throw new Error('Token chưa có quyền ghi repository.');setConn(true,'GitHub đã kết nối');if(input)input.value='';if(window.STB_ADMIN_SECURITY&&window.STB_ADMIN_SECURITY.rememberToken)window.STB_ADMIN_SECURITY.rememberToken(token());await loadRemote();toast('Kết nối GitHub thành công.','ok');}catch(e){setConn(false,'Kết nối lỗi');toast(e.message,'err');}}
async function loadRemote(){try{var f=await api('/repos/'+OWNER+'/'+REPO+'/contents/'+CONTENT_FILE+'?ref='+BRANCH);contentState=parseAssign(decode64(f.content));contentInitial=clone(contentState);contentSha=f.sha||'';contentDirty=false;clearDraft();renderAll();updateSaveUI();toast('Đã tải nội dung Landing Page mới nhất.','ok');}catch(e){toast('Không tải được nội dung: '+e.message,'err');}}
async function saveRemote(){if(!contentDirty){toast('Không có thay đổi nội dung mới.');return;}if(!token()){showPage('settings');toast('Hãy kết nối GitHub trước khi lưu.','err');return;}var b=$('#saveBtn');try{b.disabled=true;b.textContent='Đang lưu…';var body={message:'Update Landing Page content from Admin Center',content:encode64(serializeContent()),branch:BRANCH};if(contentSha)body.sha=contentSha;var r=await api('/repos/'+OWNER+'/'+REPO+'/contents/'+CONTENT_FILE,{method:'PUT',body:JSON.stringify(body)});contentSha=r.content&&r.content.sha||contentSha;contentDirty=false;clearDraft();updateSaveUI();toast('Đã lưu nội dung. GitHub Pages sẽ tự cập nhật.','ok');checkDeploy();}catch(e){toast('Lưu thất bại: '+e.message,'err');updateSaveUI();}finally{b.disabled=false;}}
async function checkDeploy(){var badge=$('#deployBadge');if(!badge)return;try{var r=await fetch('https://api.github.com/repos/'+OWNER+'/'+REPO+'/pages');var j=await r.json();var st=j.status||'unknown';badge.textContent='Pages: '+st;badge.className='tag '+(st==='built'?'ok':st==='errored'?'hidden':'manual');}catch(e){badge.textContent='Pages';}}
function ensureStructure(){contentState.site=contentState.site||{};contentState.seo=contentState.seo||{};contentState.theme=contentState.theme||{template:'premium-navy'};contentState.hero=contentState.hero||{};contentState.categories=Array.isArray(contentState.categories)?contentState.categories:[];contentState.banners=Array.isArray(contentState.banners)&&contentState.banners.length?contentState.banners:[{id:'banner-1',enabled:true,title:'',subtitle:'',ctaLabel:'',ctaUrl:'#calculator',image:''}];contentState.popups=Array.isArray(contentState.popups)&&contentState.popups.length?contentState.popups:[{id:'popup-1',name:'Popup',template:'announcement',enabled:false,status:'draft',eyebrow:'',title:'',body:'',highlight:'',image:'',ctaLabel:'Xem chi tiết',ctaUrl:'#',secondaryLabel:'Để sau',frequency:'session',delay:1100}];contentState.faqs=Array.isArray(contentState.faqs)?contentState.faqs:[];}
function bindContentInputs(){$$('[data-content]').forEach(function(el){var path=el.dataset.content,val=getPath(contentState,path);if(el.type==='checkbox')el.checked=val!==false;else el.value=val==null?'':val;el.oninput=el.onchange=function(){var v=el.type==='checkbox'?el.checked:(el.type==='number'?Number(el.value||0):el.value);setPath(contentState,path,v);markDirty();renderPreviews();renderStats();};});renderPreviews();}
function renderPreviews(){$$('[data-preview-content]').forEach(function(img){var v=getPath(contentState,img.dataset.previewContent);img.src=v||'assets/logo-tien-bao.png';});renderSeoPreview();}
function renderStats(){var c=$('#statCategories'),f=$('#statFaq'),b=$('#statBanner'),u=$('#statUpdated');if(c)c.textContent=String((contentState.categories||[]).filter(function(x){return x&&x.enabled!==false;}).length);if(f)f.textContent=String((contentState.faqs||[]).filter(function(x){return x&&x.enabled!==false;}).length);if(b)b.textContent=String((contentState.banners||[]).filter(function(x){return x&&x.enabled!==false;}).length);if(u){var d=contentState.meta&&contentState.meta.updatedAt;u.textContent=d?new Date(d).toLocaleDateString('vi-VN'):'—';}}
function renderCategories(){var root=$('#categoryEditorList');if(!root)return;root.innerHTML='';contentState.categories.forEach(function(c,i){var row=document.createElement('div');row.className='item-card';row.innerHTML='<div class="item-main"><img src="'+esc(c.image||'assets/logo-tien-bao.png')+'" alt=""><div class="item-fields"><div class="grid"><div class="field"><label>Tên danh mục</label><input data-k="name" value="'+esc(c.name||'')+'"></div><div class="field"><label>URL</label><input data-k="url" value="'+esc(c.url||'')+'"></div><div class="field full"><label>Mô tả</label><input data-k="description" value="'+esc(c.description||'')+'"></div><div class="field full"><label>Ảnh</label><input data-k="image" value="'+esc(c.image||'')+'"></div></div></div></div><div class="actions"><label class="check"><input type="checkbox" data-enable '+(c.enabled!==false?'checked':'')+'> Hiển thị</label><button class="mini" data-upload>Upload ảnh</button><button class="mini" data-up>↑</button><button class="mini" data-down>↓</button><button class="mini" data-delete>Xóa</button></div>';
root.appendChild(row);row.querySelectorAll('[data-k]').forEach(function(inp){inp.oninput=function(){contentState.categories[i][inp.dataset.k]=inp.value;markDirty();};});row.querySelector('[data-enable]').onchange=function(e){contentState.categories[i].enabled=e.target.checked;markDirty();renderStats();};row.querySelector('[data-upload]').onclick=function(){uploadContext={type:'category',index:i};$('#filePicker').click();};row.querySelector('[data-up]').onclick=function(){if(i<1)return;var x=contentState.categories.splice(i,1)[0];contentState.categories.splice(i-1,0,x);markDirty();renderCategories();};row.querySelector('[data-down]').onclick=function(){if(i>=contentState.categories.length-1)return;var x=contentState.categories.splice(i,1)[0];contentState.categories.splice(i+1,0,x);markDirty();renderCategories();};row.querySelector('[data-delete]').onclick=function(){if(confirm('Xóa danh mục này khỏi Landing Page?')){contentState.categories.splice(i,1);markDirty();renderCategories();renderStats();}};});}
function addCategory(){contentState.categories.push({id:'category-'+Date.now(),name:'Danh mục mới',description:'',image:'',url:'',enabled:true});markDirty();renderCategories();renderStats();}
function renderFaqs(){var root=$('#faqEditorList');if(!root)return;root.innerHTML='';contentState.faqs.forEach(function(f,i){var row=document.createElement('div');row.className='item-card';row.innerHTML='<div class="grid"><div class="field full"><label>Câu hỏi</label><input data-k="question" value="'+esc(f.question||'')+'"></div><div class="field full"><label>Trả lời</label><textarea data-k="answer">'+esc(f.answer||'')+'</textarea></div></div><div class="actions"><label class="check"><input type="checkbox" data-enable '+(f.enabled!==false?'checked':'')+'> Hiển thị</label><button class="mini" data-copy>Nhân bản</button><button class="mini" data-up>↑</button><button class="mini" data-down>↓</button><button class="mini" data-delete>Xóa</button></div>';root.appendChild(row);row.querySelectorAll('[data-k]').forEach(function(inp){inp.oninput=function(){contentState.faqs[i][inp.dataset.k]=inp.value;markDirty();};});row.querySelector('[data-enable]').onchange=function(e){contentState.faqs[i].enabled=e.target.checked;markDirty();renderStats();};row.querySelector('[data-copy]').onclick=function(){var x=clone(contentState.faqs[i]);x.id='faq-'+Date.now();contentState.faqs.splice(i+1,0,x);markDirty();renderFaqs();renderStats();};row.querySelector('[data-up]').onclick=function(){if(i<1)return;var x=contentState.faqs.splice(i,1)[0];contentState.faqs.splice(i-1,0,x);markDirty();renderFaqs();};row.querySelector('[data-down]').onclick=function(){if(i>=contentState.faqs.length-1)return;var x=contentState.faqs.splice(i,1)[0];contentState.faqs.splice(i+1,0,x);markDirty();renderFaqs();};row.querySelector('[data-delete]').onclick=function(){if(confirm('Xóa FAQ này?')){contentState.faqs.splice(i,1);markDirty();renderFaqs();renderStats();}};});}
function addFaq(){contentState.faqs.push({id:'faq-'+Date.now(),question:'Câu hỏi mới',answer:'',enabled:true});markDirty();renderFaqs();renderStats();}
function renderSeoPreview(){var t=getPath(contentState,'seo.title')||'',d=getPath(contentState,'seo.description')||'',tc=$('#seoTitleCount'),dc=$('#seoDescCount');if(tc)tc.textContent=t.length+'/90';if(dc)dc.textContent=d.length+'/220';if($('#googleTitle'))$('#googleTitle').textContent=t;if($('#googleDescription'))$('#googleDescription').textContent=d;}
function resetSection(name){var old=contentInitial[name];if(old==null){toast('Không có dữ liệu gốc cho section này.','err');return;}if(!confirm('Hoàn tác section "'+name+'" về dữ liệu lúc mở Admin?'))return;contentState[name]=clone(old);markDirty();renderAll();toast('Đã hoàn tác section.','ok');}
function fileBase64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(String(r.result||'').split(',')[1]||'');};r.onerror=reject;r.readAsDataURL(file);});}
function slug(s){return String(s||'image').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9.]+/g,'-').replace(/^-+|-+$/g,'');}
async function uploadFile(file){if(!file)return;if(!token()){showPage('settings');toast('Kết nối GitHub trước khi upload ảnh.','err');return;}if(file.size>8*1024*1024){toast('Ảnh lớn hơn 8MB. Hãy nén ảnh trước.','err');return;}try{var path='assets/admin/content/'+Date.now()+'-'+slug(file.name);await api('/repos/'+OWNER+'/'+REPO+'/contents/'+path,{method:'PUT',body:JSON.stringify({message:'Upload Landing Page image from Admin Center',content:await fileBase64(file),branch:BRANCH})});if(uploadContext&&uploadContext.type==='category'){contentState.categories[uploadContext.index].image=path;markDirty();renderCategories();}else if(uploadContext&&uploadContext.type==='content'){setPath(contentState,uploadContext.path,path);markDirty();renderAll();}toast('Đã tải ảnh lên GitHub.','ok');}catch(e){toast('Upload ảnh thất bại: '+e.message,'err');}finally{uploadContext=null;}}
function exportData(){var blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),content:contentState},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sontienbao-landing-content-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href);},500);}
function renderUpdatedInfo(){var el=$('#lastUpdatedInfo');if(!el)return;var d=contentState.meta&&contentState.meta.updatedAt;el.textContent='Nội dung Landing Page: '+(d?new Date(d).toLocaleString('vi-VN'):'chưa có thời gian cập nhật');}
function renderAll(){ensureStructure();bindContentInputs();renderCategories();renderFaqs();renderStats();renderDraftInfo();renderUpdatedInfo();}
function showPage(name){if(['dashboard','content','seo','settings'].indexOf(name)<0)name='dashboard';$$('.page').forEach(function(p){p.classList.toggle('active',p.id==='page-'+name);});$$('.nav [data-page]').forEach(function(b){b.classList.toggle('active',b.dataset.page===name);});var names={dashboard:'Dashboard',content:'Nội dung Landing Page',seo:'SEO & giao diện',settings:'Kết nối & sao lưu'};if($('#pageTitle'))$('#pageTitle').textContent=names[name]||'Admin Center';location.hash=name;}
function injectSecurityControls(){var top=$('.topbar');if(top&&window.STB_ADMIN_SECURITY&&!$('#securityLockTop')){var lock=document.createElement('button');lock.id='securityLockTop';lock.className='btn';lock.textContent='🔒 Khóa';lock.title='Khóa Admin ngay';lock.onclick=function(){if(contentDirty&&!confirm('Bạn còn thay đổi chưa lưu. Vẫn khóa Admin?'))return;window.STB_ADMIN_SECURITY.lock();};top.insertBefore(lock,$('#saveBtn'));var settings=$('#settingsGrid');if(settings&&!$('#securityPanel')){var sec=document.createElement('section');sec.id='securityPanel';sec.className='card editor-card full-span';sec.innerHTML='<div class="section-head"><div><h2>Bảo mật Admin</h2><p class="muted">Mật khẩu không lưu trên GitHub. GitHub token được mã hóa trên thiết bị này.</p></div></div><div class="inline-actions"><button id="securityChangePassword" class="btn">Đổi mật khẩu</button><button id="securityForgetDevice" class="btn danger">Xóa bảo mật trên thiết bị</button><button id="securityLockNow" class="btn navy">Khóa ngay</button></div>';settings.appendChild(sec);$('#securityLockNow').onclick=function(){window.STB_ADMIN_SECURITY.lock();};$('#securityChangePassword').onclick=function(){window.STB_ADMIN_SECURITY.changePassword();};$('#securityForgetDevice').onclick=function(){window.STB_ADMIN_SECURITY.forgetDevice();};}}}
function bindStatic(){$$('[data-page]').forEach(function(b){b.onclick=function(){showPage(b.dataset.page);};});$$('[data-go]').forEach(function(b){b.onclick=function(){showPage(b.dataset.go);var id=b.dataset.focus;if(id)setTimeout(function(){var el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});},50);};});if($('#themeBtn'))$('#themeBtn').onclick=function(){document.body.classList.toggle('dark');localStorage.setItem('stb-admin-v2-theme',document.body.classList.contains('dark')?'dark':'light');};if($('#previewBtn'))$('#previewBtn').onclick=function(){window.open('./','_blank','noopener');};if($('#connectBtn'))$('#connectBtn').onclick=connect;if($('#disconnectBtn'))$('#disconnectBtn').onclick=function(){setToken('');setConn(false,'Chưa kết nối');toast('Đã ngắt GitHub khỏi phiên này.');};if($('#reloadBtn'))$('#reloadBtn').onclick=loadRemote;if($('#saveBtn'))$('#saveBtn').onclick=saveRemote;if($('#addCategoryBtn'))$('#addCategoryBtn').onclick=addCategory;if($('#addFaqBtn'))$('#addFaqBtn').onclick=addFaq;if($('#restoreDraftBtn'))$('#restoreDraftBtn').onclick=restoreDraft;if($('#clearDraftBtn'))$('#clearDraftBtn').onclick=function(){clearDraft();toast('Đã xóa nháp cục bộ.');};if($('#exportBtn'))$('#exportBtn').onclick=exportData;$$('[data-upload-content]').forEach(function(b){b.onclick=function(){uploadContext={type:'content',path:b.dataset.uploadContent};$('#filePicker').click();};});$$('[data-clear-content]').forEach(function(b){b.onclick=function(){setPath(contentState,b.dataset.clearContent,'');markDirty();renderAll();};});$$('[data-reset-section]').forEach(function(b){b.onclick=function(){resetSection(b.dataset.resetSection);};});if($('#filePicker'))$('#filePicker').onchange=function(){var f=this.files&&this.files[0];this.value='';uploadFile(f);};window.addEventListener('beforeunload',function(e){if(contentDirty){e.preventDefault();e.returnValue='';}});}
if(localStorage.getItem('stb-admin-v2-theme')==='dark')document.body.classList.add('dark');
bindStatic();renderAll();updateSaveUI();checkDeploy();injectSecurityControls();var initialHash=location.hash.replace('#','');showPage(initialHash||'dashboard');if(token()){setConn(true,'Đang kiểm tra…');connect();}else setConn(false,'Chưa kết nối');
})();