(function(){
'use strict';
var OWNER='phatnbt',REPO='sontienbao-v7',BRANCH='main',FILE='manual-products.js';
var state=JSON.parse(JSON.stringify(window.STB_MANUAL_PRODUCTS||{version:1,updatedAt:null,additions:[],overrides:{},hidden:[]}));
var base=Array.isArray(window.STB_PRODUCTS_BEFORE_MANUAL)?window.STB_PRODUCTS_BEFORE_MANUAL.slice():[];
var resolved=window.STB_DEFAULT_DATA&&Array.isArray(window.STB_DEFAULT_DATA.products)?window.STB_DEFAULT_DATA.products.slice():[];
var fileSha='',dirty=false,currentEdit=null;
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
function token(){return sessionStorage.getItem('stb-v7-github-token')||'';}
function setToken(v){if(v)sessionStorage.setItem('stb-v7-github-token',v);else sessionStorage.removeItem('stb-v7-github-token');}
function normUrl(u){return String(u||'').trim().replace(/\/$/,'');}
function pkey(p){if(p&&p.id)return'id:'+p.id;if(p&&p.url)return'url:'+normUrl(p.url);return'id:manual-'+Date.now();}
function money(v){v=Number(v||0);return v?v.toLocaleString('vi-VN')+' ₫':'Liên hệ';}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function toast(msg,type){var el=$('#toast');el.textContent=msg;el.className='toast show '+(type||'');clearTimeout(el._t);el._t=setTimeout(function(){el.className='toast';},4200);}
function markDirty(v){dirty=v!==false;$('#saveBtn').textContent=dirty?'Lưu thay đổi':'Đã lưu';}
async function api(path,opts){var t=token();if(!t)throw new Error('Chưa kết nối GitHub.');opts=opts||{};var headers=Object.assign({'Accept':'application/vnd.github+json','Authorization':'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'},opts.headers||{});if(opts.body)headers['Content-Type']='application/json';var r=await fetch('https://api.github.com'+path,Object.assign({},opts,{headers:headers}));var body=null;try{body=await r.json();}catch(e){}if(!r.ok)throw new Error((body&&body.message)||('GitHub API '+r.status));return body;}
function encode64(s){var u=new TextEncoder().encode(s),b='',chunk=0x8000;for(var i=0;i<u.length;i+=chunk)b+=String.fromCharCode.apply(null,u.subarray(i,i+chunk));return btoa(b);}
function decode64(s){var b=atob(String(s||'').replace(/\s/g,'')),u=new Uint8Array(b.length);for(var i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new TextDecoder().decode(u);}
function parseManual(text){var m=text.match(/window\.STB_MANUAL_PRODUCTS\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);if(!m)throw new Error('Không đọc được manual-products.js');return JSON.parse(m[1]);}
function serialize(){state.version=1;state.updatedAt=new Date().toISOString();return'window.STB_MANUAL_PRODUCTS = '+JSON.stringify(state,null,2)+';\n';}
function setConn(ok,text){var el=$('#connBadge');el.className='tag '+(ok?'sync':'hidden');el.textContent=text||(ok?'Đã kết nối':'Chưa kết nối');}
async function connect(){var v=$('#tokenInput').value.trim();if(v)setToken(v);try{var repo=await api('/repos/'+OWNER+'/'+REPO);if(repo.permissions&&repo.permissions.push===false)throw new Error('Token chưa có quyền ghi repository.');setConn(true,'GitHub đã kết nối');$('#tokenInput').value='';await loadRemote();toast('Kết nối GitHub thành công.','ok');}catch(e){setConn(false,'Kết nối lỗi');toast(e.message,'err');}}
async function loadRemote(){try{var f=await api('/repos/'+OWNER+'/'+REPO+'/contents/'+FILE+'?ref='+BRANCH);state=parseManual(decode64(f.content));fileSha=f.sha||'';markDirty(false);rebuild();toast('Đã tải lớp sản phẩm thủ công mới nhất.','ok');}catch(e){toast('Không tải được dữ liệu: '+e.message,'err');}}
async function saveRemote(){if(!token()){showPage('settings');toast('Hãy kết nối GitHub trước khi lưu.','err');return;}try{$('#saveBtn').disabled=true;$('#saveBtn').textContent='Đang lưu…';var body={message:'Update V7 manual products from Admin V2',content:encode64(serialize()),branch:BRANCH};if(fileSha)body.sha=fileSha;var r=await api('/repos/'+OWNER+'/'+REPO+'/contents/'+FILE,{method:'PUT',body:JSON.stringify(body)});fileSha=r.content&&r.content.sha||fileSha;markDirty(false);toast('Đã lưu. V7 sẽ cập nhật sau khi GitHub Pages deploy.','ok');}catch(e){toast('Lưu thất bại: '+e.message,'err');$('#saveBtn').textContent='Lưu thay đổi';}finally{$('#saveBtn').disabled=false;}}
function manualFor(p){var k=pkey(p);return state.overrides&&state.overrides[k]?state.overrides[k]:null;}
function isHidden(p){return Array.isArray(state.hidden)&&state.hidden.indexOf(pkey(p))>=0;}
function resolveAll(){var items=base.map(function(p){var o=manualFor(p);return o?Object.assign({},p,o,{manualOverride:true}):Object.assign({},p);});var map={};items.forEach(function(p){map[pkey(p)]=true;});(state.additions||[]).forEach(function(p){if(p&&!map[pkey(p)])items.push(Object.assign({manualOnly:true,enabled:true},p));});return items;}
function rebuild(){resolved=resolveAll();renderStats();renderProducts();}
function renderStats(){$('#statTotal').textContent=resolved.filter(function(p){return !isHidden(p)&&p.enabled!==false;}).length;$('#statSynced').textContent=base.length;$('#statOverride').textContent=Object.keys(state.overrides||{}).length;$('#statHidden').textContent=(state.hidden||[]).length;}
function sourceOf(p){if(p.manualOnly)return'manual';if(manualFor(p))return'override';if(isHidden(p))return'hidden';return'sync';}
function sourceTag(p){var s=sourceOf(p);if(s==='manual')return'<span class="tag manual">Thêm thủ công</span>';if(s==='override')return'<span class="tag manual">Đã sửa thủ công</span>';if(s==='hidden')return'<span class="tag hidden">Đang ẩn</span>';return'<span class="tag sync">Tự đồng bộ</span>';}
function getAllForTable(){var list=resolveAll();var existing={};list.forEach(function(p){existing[pkey(p)]=true;});base.forEach(function(p){if(isHidden(p)&&!existing[pkey(p)])list.push(Object.assign({},p));});return list;}
function renderProducts(){var q=String($('#productSearch').value||'').toLowerCase(),filter=$('#sourceFilter').value;var rows=$('#productRows');rows.innerHTML='';var list=getAllForTable().filter(function(p){var source=sourceOf(p);if(filter!=='all'&&source!==filter)return false;var hay=[p.name,p.brand,p.category,p.url].join(' ').toLowerCase();return !q||hay.indexOf(q)>=0;});$('#productEmpty').style.display=list.length?'none':'block';list.forEach(function(p){var tr=document.createElement('tr'),hidden=isHidden(p),source=sourceOf(p);tr.innerHTML='<td><div style="display:flex;align-items:center;gap:10px"><img src="'+esc(p.image||'assets/logo-tien-bao.png')+'" alt=""><div><div class="product-name">'+esc(p.name||'Sản phẩm')+'</div><div class="muted">'+esc(p.brand||'')+'</div></div></div></td><td>'+sourceTag(p)+'</td><td>'+esc(p.category||'—')+'</td><td><b>'+esc(money(p.price))+'</b>'+(p.oldPrice?'<div class="muted"><s>'+esc(money(p.oldPrice))+'</s></div>':'')+'</td><td>'+(hidden?'<span class="tag hidden">Ẩn</span>':(p.enabled===false?'<span class="tag hidden">Tắt</span>':'<span class="tag sync">Hiển thị</span>'))+'</td><td><div class="actions"><button class="mini" data-edit>Sửa</button>'+(source==='override'?'<button class="mini" data-restore>Trả về sync</button>':'')+(hidden?'<button class="mini" data-show>Hiện lại</button>':'<button class="mini" data-hide>Ẩn</button>')+(source==='manual'?'<button class="mini" data-delete>Xóa</button>':'')+'</div></td>';rows.appendChild(tr);tr.querySelector('[data-edit]').onclick=function(){openEdit(p);};var b=tr.querySelector('[data-restore]');if(b)b.onclick=function(){delete state.overrides[pkey(p)];state.hidden=state.hidden.filter(function(k){return k!==pkey(p);});markDirty();rebuild();};b=tr.querySelector('[data-hide]');if(b)b.onclick=function(){if(state.hidden.indexOf(pkey(p))<0)state.hidden.push(pkey(p));markDirty();rebuild();};b=tr.querySelector('[data-show]');if(b)b.onclick=function(){state.hidden=state.hidden.filter(function(k){return k!==pkey(p);});markDirty();rebuild();};b=tr.querySelector('[data-delete]');if(b)b.onclick=function(){if(confirm('Xóa sản phẩm thủ công này?')){state.additions=state.additions.filter(function(x){return pkey(x)!==pkey(p);});markDirty();rebuild();}};});}
function fillForm(p){$('#fName').value=p.name||'';$('#fBrand').value=p.brand||'';$('#fCategory').value=p.category||'';$('#fBadge').value=p.badge||'';$('#fDescription').value=p.description||'';$('#fPrice').value=Number(p.price||0);$('#fOldPrice').value=Number(p.oldPrice||0);$('#fPricePrefix').value=p.pricePrefix||'';$('#fUnit').value=p.unit||'';$('#fUrl').value=p.url||'';$('#fImage').value=p.image||'';$('#fFeatured').checked=p.featured===true;$('#fEnabled').checked=p.enabled!==false;updatePreview();}
function openEdit(p){currentEdit=p;$('#modalTitle').textContent=p.manualOnly?'Sửa sản phẩm thủ công':'Chỉnh sửa sản phẩm';$('#editKey').value=pkey(p);$('#editMode').value=p.manualOnly?'manual':'override';fillForm(p);$('#productModal').classList.add('show');}
function openAdd(){var p={id:'manual-'+Date.now(),name:'',brand:'JOTUN',category:'Sản phẩm',description:'',image:'',price:0,oldPrice:0,pricePrefix:'',unit:'',badge:'',featured:true,enabled:true,url:'',manualOnly:true};currentEdit=p;$('#modalTitle').textContent='Thêm sản phẩm mới';$('#editKey').value=pkey(p);$('#editMode').value='new';fillForm(p);$('#productModal').classList.add('show');}
function closeModal(){$('#productModal').classList.remove('show');currentEdit=null;}
function formData(){return{name:$('#fName').value.trim(),brand:$('#fBrand').value.trim(),category:$('#fCategory').value.trim(),badge:$('#fBadge').value.trim(),description:$('#fDescription').value.trim(),price:Number($('#fPrice').value||0),oldPrice:Number($('#fOldPrice').value||0),pricePrefix:$('#fPricePrefix').value.trim(),unit:$('#fUnit').value.trim(),url:$('#fUrl').value.trim(),image:$('#fImage').value.trim(),featured:$('#fFeatured').checked,enabled:$('#fEnabled').checked};}
function submitProduct(e){e.preventDefault();var data=formData(),mode=$('#editMode').value,key=$('#editKey').value;if(!data.name){toast('Tên sản phẩm không được để trống.','err');return;}if(mode==='new'){data.id=key.replace(/^id:/,'');data.manualOnly=true;state.additions.push(data);}else if(mode==='manual'){var idx=state.additions.findIndex(function(p){return pkey(p)===key;});if(idx>=0)state.additions[idx]=Object.assign({},state.additions[idx],data);}else{state.overrides[key]=data;state.hidden=state.hidden.filter(function(k){return k!==key;});}markDirty();closeModal();rebuild();toast('Đã áp dụng thay đổi. Bấm “Lưu thay đổi” để cập nhật V7.','ok');}
function updatePreview(){var v=$('#fImage').value.trim();$('#imagePreview').src=v||'assets/logo-tien-bao.png';}
function fileBase64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(String(r.result||'').split(',')[1]||'');};r.onerror=reject;r.readAsDataURL(file);});}
function slug(s){return String(s||'image').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9.]+/g,'-').replace(/^-+|-+$/g,'');}
async function uploadImage(file){if(!file)return;if(!token()){showPage('settings');toast('Kết nối GitHub trước khi upload ảnh.','err');return;}if(file.size>8*1024*1024){toast('Ảnh lớn hơn 8MB. Hãy nén ảnh trước.','err');return;}try{var path='assets/admin/products/'+Date.now()+'-'+slug(file.name);await api('/repos/'+OWNER+'/'+REPO+'/contents/'+path,{method:'PUT',body:JSON.stringify({message:'Upload product image from Admin V2',content:await fileBase64(file),branch:BRANCH})});$('#fImage').value=path;updatePreview();toast('Đã tải ảnh lên GitHub.','ok');}catch(e){toast('Upload ảnh thất bại: '+e.message,'err');}}
function showPage(name){$$('.page').forEach(function(p){p.classList.toggle('active',p.id==='page-'+name);});$$('.nav [data-page]').forEach(function(b){b.classList.toggle('active',b.dataset.page===name);});var names={dashboard:'Dashboard',products:'Sản phẩm',content:'Nội dung',settings:'Kết nối'};$('#pageTitle').textContent=names[name]||'Admin V2';}
$$('[data-page]').forEach(function(b){b.onclick=function(){showPage(b.dataset.page);};});$$('[data-go]').forEach(function(a){a.onclick=function(e){e.preventDefault();showPage(a.dataset.go);};});
$('#themeBtn').onclick=function(){document.body.classList.toggle('dark');localStorage.setItem('stb-admin-v2-theme',document.body.classList.contains('dark')?'dark':'light');};if(localStorage.getItem('stb-admin-v2-theme')==='dark')document.body.classList.add('dark');
$('#connectBtn').onclick=connect;$('#disconnectBtn').onclick=function(){setToken('');setConn(false,'Chưa kết nối');toast('Đã xóa token khỏi phiên trình duyệt.');};$('#reloadBtn').onclick=loadRemote;$('#saveBtn').onclick=saveRemote;$('#addProductBtn').onclick=openAdd;$('#cancelModal').onclick=closeModal;$('#productForm').onsubmit=submitProduct;$('#productSearch').oninput=renderProducts;$('#sourceFilter').onchange=renderProducts;$('#fImage').oninput=updatePreview;$('#uploadImageBtn').onclick=function(){$('#filePicker').click();};$('#filePicker').onchange=function(){var f=this.files&&this.files[0];this.value='';uploadImage(f);};$('#productModal').onclick=function(e){if(e.target===this)closeModal();};
rebuild();markDirty(false);if(token()){setConn(true,'Đang kiểm tra…');connect();}else setConn(false,'Chưa kết nối');
})();
