(function(){
'use strict';
var VAULT_KEY='stb-admin-v2-secure-vault-v1';
var AUTH_KEY='stb-admin-v2-authenticated';
var TOKEN_KEY='stb-v7-github-token';
var FAIL_KEY='stb-admin-v2-login-fails';
var LOCK_KEY='stb-admin-v2-login-lock-until';
var CHECK='STB_ADMIN_V2_UNLOCKED';
var ITERATIONS=310000;
var OWNER='phatnbt',REPO='sontienbao-v7';
var shell=document.querySelector('.shell');
var currentKey=null;
if(shell)shell.style.display='none';
function b64(bytes){var s='';for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return btoa(s);}
function unb64(s){var x=atob(s),u=new Uint8Array(x.length);for(var i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u;}
function textBytes(s){return new TextEncoder().encode(s);}
function bytesText(b){return new TextDecoder().decode(b);}
async function derive(password,salt){var material=await crypto.subtle.importKey('raw',textBytes(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt,iterations:ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encrypt(key,text){var iv=crypto.getRandomValues(new Uint8Array(12));var data=await crypto.subtle.encrypt({name:'AES-GCM',iv:iv},key,textBytes(text));return{iv:b64(iv),data:b64(new Uint8Array(data))};}
async function decrypt(key,obj){var data=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(obj.iv)},key,unb64(obj.data));return bytesText(new Uint8Array(data));}
function readVault(){try{return JSON.parse(localStorage.getItem(VAULT_KEY)||'null');}catch(e){return null;}}
function writeVault(v){localStorage.setItem(VAULT_KEY,JSON.stringify(v));}
function styleGate(){if(document.getElementById('stbSecurityStyle'))return;var st=document.createElement('style');st.id='stbSecurityStyle';st.textContent='.stb-security-locked{overflow:hidden;background:#07131f!important}.stb-security-gate{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:20px;background:radial-gradient(circle at 20% 10%,#173d59 0,#07131f 42%,#040b11 100%);color:#ecf3f8}.stb-security-card{width:min(440px,100%);background:rgba(9,22,34,.96);border:1px solid rgba(255,255,255,.12);border-radius:22px;padding:28px;box-shadow:0 30px 90px rgba(0,0,0,.45)}.stb-security-logo{width:58px;height:58px;object-fit:contain;background:white;border-radius:15px;padding:6px;margin-bottom:18px}.stb-security-card h1{font:800 25px/1.2 system-ui;margin:0 0 7px}.stb-security-card p{font:14px/1.5 system-ui;color:#9fb3c1;margin:0 0 18px}.stb-security-field{display:flex;flex-direction:column;gap:6px;margin:12px 0}.stb-security-field label{font:700 12px system-ui;color:#bed0dc}.stb-security-field input{width:100%;border:1px solid #355064;background:#0a1824;color:#fff;border-radius:11px;padding:12px 13px;outline:none;font:15px system-ui}.stb-security-field input:focus{border-color:#7aa8c8;box-shadow:0 0 0 3px rgba(100,160,200,.14)}.stb-security-btn{width:100%;border:0;border-radius:11px;padding:12px 14px;background:#d72620;color:white;font:800 15px system-ui;cursor:pointer;margin-top:8px}.stb-security-btn:disabled{opacity:.55;cursor:wait}.stb-security-secondary{width:100%;border:1px solid #355064;border-radius:11px;padding:10px 12px;background:transparent;color:#c6d5df;font:700 13px system-ui;cursor:pointer;margin-top:9px}.stb-security-msg{min-height:20px;margin-top:11px!important;color:#ffb4ae!important}.stb-security-note{font-size:12px!important;color:#8196a5!important;margin-top:14px!important}.stb-security-status{display:inline-flex;align-items:center;gap:7px;font:700 11px system-ui;color:#8fd8b9;margin-bottom:12px}.stb-security-status:before{content:"";width:8px;height:8px;border-radius:50%;background:#29b579}';document.head.appendChild(st);}
function removeOverlay(){var old=document.getElementById('stbSecurityGate');if(old)old.remove();document.body.classList.remove('stb-security-locked');}
function gateBase(){styleGate();removeOverlay();document.body.classList.add('stb-security-locked');var wrap=document.createElement('div');wrap.id='stbSecurityGate';wrap.className='stb-security-gate';document.body.appendChild(wrap);return wrap;}
function setMsg(msg){var el=document.getElementById('stbSecurityMsg');if(el)el.textContent=msg||'';}
function lockRemaining(){var until=Number(sessionStorage.getItem(LOCK_KEY)||0);return Math.max(0,until-Date.now());}
function failLogin(){var n=Number(sessionStorage.getItem(FAIL_KEY)||0)+1;if(n>=5){sessionStorage.setItem(FAIL_KEY,'0');sessionStorage.setItem(LOCK_KEY,String(Date.now()+30000));return 30000;}sessionStorage.setItem(FAIL_KEY,String(n));return 0;}
function clearFails(){sessionStorage.removeItem(FAIL_KEY);sessionStorage.removeItem(LOCK_KEY);}
async function verifyPat(t){var r=await fetch('https://api.github.com/repos/'+OWNER+'/'+REPO,{headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+t,'X-GitHub-Api-Version':'2022-11-28'}});var body={};try{body=await r.json();}catch(e){}if(!r.ok)throw new Error('Token GitHub không hợp lệ hoặc không truy cập được repo.');if(body.permissions&&body.permissions.push===false)throw new Error('Token chưa có quyền Contents: Read and write.');}
async function createVault(password,pat){var salt=crypto.getRandomValues(new Uint8Array(16));var key=await derive(password,salt);var check=await encrypt(key,CHECK);var tokenBox=pat?await encrypt(key,pat):null;writeVault({version:1,kdf:'PBKDF2-SHA256',iterations:ITERATIONS,salt:b64(salt),check:check,token:tokenBox,createdAt:new Date().toISOString()});currentKey=key;if(pat)sessionStorage.setItem(TOKEN_KEY,pat);sessionStorage.setItem(AUTH_KEY,'1');clearFails();}
async function unlockVault(password){var vault=readVault();if(!vault)throw new Error('Chưa thiết lập bảo mật.');var key=await derive(password,unb64(vault.salt));var ok=await decrypt(key,vault.check);if(ok!==CHECK)throw new Error('Mật khẩu không đúng.');currentKey=key;if(vault.token){var pat=await decrypt(key,vault.token);if(pat)sessionStorage.setItem(TOKEN_KEY,pat);}sessionStorage.setItem(AUTH_KEY,'1');clearFails();}
function loadCore(){removeOverlay();if(shell)shell.style.display='grid';if(document.querySelector('script[data-stb-admin-core]'))return;var s=document.createElement('script');s.src='admin-core.js';s.dataset.stbAdminCore='1';document.body.appendChild(s);}
function showSetup(resetMode){var wrap=gateBase();wrap.innerHTML='<div class="stb-security-card"><img class="stb-security-logo" src="assets/logo-tien-bao.png" alt=""><div class="stb-security-status">Thiết lập bảo mật cục bộ</div><h1>'+(resetMode?'Đặt lại bảo mật Admin':'Tạo mật khẩu Admin')+'</h1><p>Mật khẩu không lưu trong source code hay GitHub. Bạn tự đặt tại đây.</p><div class="stb-security-field"><label>Mật khẩu mới</label><input id="stbSetupPass" type="password" autocomplete="new-password" placeholder="Tối thiểu 12 ký tự"></div><div class="stb-security-field"><label>Nhập lại mật khẩu</label><input id="stbSetupPass2" type="password" autocomplete="new-password"></div><div class="stb-security-field"><label>GitHub token của Admin</label><input id="stbSetupPat" type="password" autocomplete="off" placeholder="github_pat_..."></div><button id="stbSetupBtn" class="stb-security-btn">'+(resetMode?'Xác minh & đặt lại':'Tạo bảo mật Admin')+'</button><p id="stbSecurityMsg" class="stb-security-msg"></p><p class="stb-security-note">Token được xác minh trực tiếp với GitHub rồi mã hóa trên thiết bị bằng mật khẩu của bạn.</p></div>';var btn=document.getElementById('stbSetupBtn');btn.onclick=async function(){var p=document.getElementById('stbSetupPass').value,p2=document.getElementById('stbSetupPass2').value,pat=document.getElementById('stbSetupPat').value.trim();if(p.length<12){setMsg('Mật khẩu cần ít nhất 12 ký tự.');return;}if(p!==p2){setMsg('Hai mật khẩu chưa giống nhau.');return;}if(!pat){setMsg('Cần GitHub token để xác nhận bạn là Admin.');return;}try{btn.disabled=true;btn.textContent='Đang xác minh…';await verifyPat(pat);await createVault(p,pat);loadCore();}catch(e){setMsg(e.message||'Không thể thiết lập bảo mật.');}finally{btn.disabled=false;btn.textContent=resetMode?'Xác minh & đặt lại':'Tạo bảo mật Admin';}};}
function showLogin(){var wrap=gateBase();wrap.innerHTML='<div class="stb-security-card"><img class="stb-security-logo" src="assets/logo-tien-bao.png" alt=""><div class="stb-security-status">Admin được khóa</div><h1>Đăng nhập Admin</h1><p>Nhập mật khẩu Admin để mở bảng quản trị Sơn Tiến Bảo.</p><div class="stb-security-field"><label>Mật khẩu</label><input id="stbLoginPass" type="password" autocomplete="current-password" autofocus></div><button id="stbLoginBtn" class="stb-security-btn">Đăng nhập</button><button id="stbForgotBtn" class="stb-security-secondary">Quên mật khẩu / đổi thiết bị</button><p id="stbSecurityMsg" class="stb-security-msg"></p><p class="stb-security-note">Mật khẩu không được gửi lên GitHub và không xuất hiện trong mã nguồn website.</p></div>';var input=document.getElementById('stbLoginPass'),btn=document.getElementById('stbLoginBtn');function updateLock(){var ms=lockRemaining();if(ms>0){btn.disabled=true;setMsg('Nhập sai nhiều lần. Thử lại sau '+Math.ceil(ms/1000)+' giây.');setTimeout(updateLock,1000);}else{btn.disabled=false;if((document.getElementById('stbSecurityMsg').textContent||'').indexOf('Nhập sai nhiều lần')>=0)setMsg('');}}updateLock();async function go(){if(lockRemaining()>0)return;var p=input.value;if(!p){setMsg('Hãy nhập mật khẩu.');return;}try{btn.disabled=true;btn.textContent='Đang mở…';await unlockVault(p);loadCore();}catch(e){var wait=failLogin();setMsg(wait?'Sai mật khẩu. Admin tạm khóa 30 giây.':'Mật khẩu không đúng.');input.value='';input.focus();}finally{btn.disabled=false;btn.textContent='Đăng nhập';}}btn.onclick=go;input.onkeydown=function(e){if(e.key==='Enter')go();};document.getElementById('stbForgotBtn').onclick=function(){if(confirm('Đặt lại bảo mật trên thiết bị này? Bạn sẽ cần GitHub token để xác minh quyền Admin.'))showSetup(true);};}
async function rememberToken(pat){if(!currentKey||!pat)return;try{var vault=readVault();if(!vault)return;vault.token=await encrypt(currentKey,pat);vault.updatedAt=new Date().toISOString();writeVault(vault);}catch(e){}}
function lock(){sessionStorage.removeItem(AUTH_KEY);sessionStorage.removeItem(TOKEN_KEY);currentKey=null;location.reload();}
function forgetDevice(){if(!confirm('Xóa mật khẩu và token đã mã hóa trên thiết bị này? Bạn sẽ cần GitHub token để thiết lập lại.'))return;localStorage.removeItem(VAULT_KEY);sessionStorage.removeItem(AUTH_KEY);sessionStorage.removeItem(TOKEN_KEY);currentKey=null;location.reload();}
function changePassword(){if(!currentKey){lock();return;}var wrap=gateBase();if(shell)shell.style.display='none';wrap.innerHTML='<div class="stb-security-card"><img class="stb-security-logo" src="assets/logo-tien-bao.png" alt=""><h1>Đổi mật khẩu Admin</h1><p>Mật khẩu mới sẽ mã hóa lại GitHub token đang lưu trên thiết bị.</p><div class="stb-security-field"><label>Mật khẩu mới</label><input id="stbChange1" type="password" autocomplete="new-password"></div><div class="stb-security-field"><label>Nhập lại mật khẩu</label><input id="stbChange2" type="password" autocomplete="new-password"></div><button id="stbChangeBtn" class="stb-security-btn">Đổi mật khẩu</button><button id="stbChangeCancel" class="stb-security-secondary">Hủy</button><p id="stbSecurityMsg" class="stb-security-msg"></p></div>';document.getElementById('stbChangeCancel').onclick=function(){removeOverlay();if(shell)shell.style.display='grid';};document.getElementById('stbChangeBtn').onclick=async function(){var p=document.getElementById('stbChange1').value,p2=document.getElementById('stbChange2').value;if(p.length<12){setMsg('Mật khẩu cần ít nhất 12 ký tự.');return;}if(p!==p2){setMsg('Hai mật khẩu chưa giống nhau.');return;}try{await createVault(p,sessionStorage.getItem(TOKEN_KEY)||'');removeOverlay();if(shell)shell.style.display='grid';alert('Đã đổi mật khẩu Admin.');}catch(e){setMsg('Không thể đổi mật khẩu.');}};}
window.STB_ADMIN_SECURITY={rememberToken:rememberToken,lock:lock,forgetDevice:forgetDevice,changePassword:changePassword};
if(!window.crypto||!crypto.subtle){alert('Trình duyệt này không hỗ trợ Web Crypto. Không thể mở Admin an toàn.');return;}
if(!readVault())showSetup(false);else showLogin();
})();
